### ISSUE TITLE
mkbranch is hard to learn to use and no longer useful

### ISSUE THREAD

**Issue by exarkun** [twisted/twisted-dev-tools#6]
```
(twisted-dev)exarkun@phonon:~/Projects/twisted/review$ mkbranch 
/home/exarkun/Environments/twisted-dev/bin/mkbranch: Wrong number of arguments.
/home/exarkun/Environments/twisted-dev/bin/mkbranch: Try --help for usage details.
(twisted-dev)exarkun@phonon:~/Projects/twisted/review$ mkbranch --help
Usage: mkbranch [options]
Options:
      --version  Display Twisted version and exit.
      --help     Display this help and exit.
(twisted-dev)exarkun@phonon:~/Projects/twisted/review$
```

Nothing here tells me what arguments to pass.

---------

with migration to git, this is of little use so we can remove it.

**Comment by rodrigc** [comment]
Now that Twisted has moved to GitHub, I see little value in maintaining
the mkbranch script.
I recommend that this issue be closed.

**Comment by adiroiban** [comment]
Do we have a follow up ticket for removing the mkbranch script from this repo?

Maybe we can re-target this ticket and update the description to conclude that mkbranch script should be removed

**Comment by rodrigc** [comment]
There is no follow up ticket.  I think updating this ticket for removal of mkbranch is fine.
I wasn't sure how many people care about mkbranch
